### ISSUE TITLE
emp info broken

### ISSUE THREAD

**Issue by pikeas** [remind101/emp#13]
```
$ emp create foo
Created foo.

$ emp info -a foo
error: Unexpected error: 404 Not Found
```

**Comment by ejholmes** [comment]
This endpoint is unimplemented atm. We should implement this and change the [CLI to display App name and ID](https://github.com/remind101/emp/blob/master/info.go#L17-L30). Displaying the ID would be useful when you need to find the ECS services in the AWS console.


@benjamin-guillet wanna tackle this when you're finished up with what you're working on?

**Comment by phobologic** [comment]
Might be worth giving the hostname if one is supplied, and the internal hostname maybe (though that's pretty easy to figure out, might save some questions):

```
Name:     acme-inc
Web URL:  https://acme-inc.remind.com/
Internal URL:  http://acme-inc.empire/
```

?

**Comment by benjamin-guillet** [comment]
@ejholmes yup.

**Comment by benjamin-guillet** [comment]
@pikeas basic implementation in https://github.com/remind101/empire/pull/619 and https://github.com/remind101/emp/pull/17
