### ISSUE TITLE
emp fails with self-signed certificates

### ISSUE THREAD

**Issue by brianz** [remind101/emp#18]
`emp` fails when using a self-signed ssl certificate.  To generate and upload a new ssl certificate:

http://git.io/vYPHI

When that certificate is used for Empire, commands result in the following:

```
$ emp apps
error: Get https://empire.brianz.bz/apps: x509: certificate signed by unknown authority
```

This certificate was added to Keychain on my Mac, and Safari seems happy with it:

<img width="709" alt="screenshot 2015-07-27 16 52 47" src="https://cloud.githubusercontent.com/assets/190550/8919843/10ce819a-3480-11e5-9cb1-0af05bd1dbfe.png">

<img width="568" alt="screenshot 2015-07-27 16 41 50" src="https://cloud.githubusercontent.com/assets/190550/8919845/159ad264-3480-11e5-8031-bb74a55a75b1.png">

@phobologic suggests this may be an issue with the way Go handles certs:

https://groups.google.com/forum/#!topic/golang-nuts/v5ShM8R7Tdc

**Comment by mhahn** [comment]
hi @brianz :)

i'm having the same issue as well.

**Comment by mhahn** [comment]
nevermind, my issue was that I had trusted my private CA, which is different than this self signed issue.

**Comment by brianz** [comment]
I need to go back and try this again.  It could be that I didn't sign the certificate correctly.  Also, in the attached gist I'm not creating a CA.  Bottom line, self-signed ssl certs + ELBS can be tricky, not 100% sure this is an issue with `emp`.  I'll follow up again after more testing.

**Comment by phobologic** [comment]
Yeah, honestly, I'm not sure how you can tell your OS that it should trust certificates signed by themselves - I don't believe it's possible.

That said, you should create a CA (tons of docs on this on the internet), then make sure you import the CA public key into your OS.  Then use that to sign a key, and everything will be good.

We could include a 'ignore verification' with the CLI, that would make this work, but it could also lead to some dangerous situations.

I'm going to go ahead and close this for now - but @brianz or @mhahn if you see this issue with private CA signed certs, go ahead and re-open.
