### ISSUE TITLE
Emp run in non-interactive shell: error: inappropriate ioctl for device

### ISSUE THREAD

**Issue by corentone** [remind101/emp#28]
Hello,

When running `emp run` in non-interactive shell (Jenkins execute shell), I get an ioctl error:
```
error: inappropriate ioctl for device
```
I tried to use `screen -c "emp run -- python manage.py help"` to fake a TTY and it seems that the command just comes back empty. I am not sure if it ran as the output is lost (which is not the case for other processes I run with `screen -c` to test).

I've tried detached but it is not implemented for ECS.
Would you have any advice on how to run it or is it a bug?
Locally runs perfectly!
Thanks!
Co

**Comment by corentone** [comment]
I ended up using expect:
```
#!/usr/bin/expect -f

#necessary timeout since tasks can be pretty long (pull the image, start...)
set timeout -1
spawn emp run -a APP bash
# This expect corresponds to the shell prompt
expect "# "
send "python manage.py help\r"
expect "# "
send "exit\r"
expect eof 
```

The solution is valid for me, we can use this issue to try to fix the tty problems or we can close it as "Won't fix". Maybe the doc could benefit from the expect suggestion.

**Comment by ejholmes** [comment]
While, there may be a solution for running an attached process without a tty, the end goal is to [support detached runs](https://github.com/remind101/empire/issues/570) (using the `-d` flag) within Empire itself for long running tasks like migrations. I'll close this for now as a wontfix.

Have you tried setting `TERM=screen-256color` before running `emp run`?

**Comment by corentone** [comment]
I tried `TERM=xterm` I think.
I agree about detached, as long as we have a way to know the result somehow?

Thanks!
